spring:
  application:
    name: configServer

  cloud:
    config.server.git:
      uri: https://github.com/federicomartinlara1976/config.git
      default-label: master 
      username: federicomartinlara1976
      password: ${GIT_PASSWORD}

server:
  port: 8888
