CREATE TABLE customer (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(255),
    phone VARCHAR(255),
    iban VARCHAR(255),
    surname VARCHAR(255),
    address VARCHAR(255)
);

CREATE TABLE customer_product (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    customerId BIGINT,
    productId BIGINT
);

CREATE SEQUENCE "CUSTOMER_SEQ" 
MINVALUE 1 
MAXVALUE 999999999 
INCREMENT BY 50 
START WITH 202700 
NOCACHE 
NOCYCLE;

CREATE SEQUENCE "CUSTOMER_PRODUCT_SEQ" 
MINVALUE 1 
MAXVALUE 999999999 
INCREMENT BY 50 
START WITH 202700 
NOCACHE 
NOCYCLE;